blank_issues_enabled: true

too bad for you

contact_links:
  - name: Ask A Question
    url: https://github.com/3b1b/manim/discussions/categories/q-a
    about: Please ask questions you encountered here.
